# Project identification
sonar.projectKey=curves-and-surfaces
sonar.projectName=Curves and Surfaces
sonar.projectVersion=1.0

# Source code location
sonar.sources=src
sonar.tests=test

# Language
sonar.language=ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Encoding of source files
sonar.sourceEncoding=UTF-8
