import { COMPLEX_VECTOR_SPACE_NAME, PROJECTIVE_COMPLEX_VECTOR_SPACE_NAME, PROJECTIVE_VECTOR_SPACE_NAME, REAL_VECTOR_SPACE_NAME } from "./VectorSpaceResolvers";

export const DEFAULT_REAL_VECTOR_SPACE_NAME = "Default " + REAL_VECTOR_SPACE_NAME;
export const DEFAULT_COMPLEX_VECTOR_SPACE_NAME = "Default " + COMPLEX_VECTOR_SPACE_NAME;
export const DEFAULT_PROJECTIVE_VECTOR_SPACE_NAME = "Default " + PROJECTIVE_VECTOR_SPACE_NAME;
export const DEFAULT_PROJECTIVE_COMPLEX_VECTOR_SPACE_NAME = "Default " + PROJECTIVE_COMPLEX_VECTOR_SPACE_NAME;
export const LOCATION_INDEX_INTO_DEFAULT_VECTOR_SPACE_ID = 4;
export const DEFAULT_VSPACE_INDEX_INITIAL_VALUE = 1;
